USE codeup_test_db;

TRUNCATE albums;

INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 49.2, 'Pop, post-disco, funk, rock'),
       ('Eagles', 'Their Greatest Hits', 1976, 41.2, 'Country rock, soft rock, folk rock'),
       ('Whitney', 'The Bodyguard', 1992, 32.4, 'R&B, soul, pop'),
       ('Eagles', 'Hotel California', 1976, 31.5, 'Soft rock'),
       ('Shania Twain', 'Come On Over', 1997, 29.6, 'Country, pop'),
       ('AC/DC', 'Back in Black', 1980, 29.5, 'Hard rock'),
       ('Fleetwood Mac', 'Rumours', 1977, 27.9, 'Soft rock'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 24.4, 'Progressive Rock'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 21.7, 'Hard rock, glam rock, progressive rock'),
       ('Bee Bees', 'Saturday Night Fever', 1977, 21.6, 'Disco'),
       ('Various artists','Grease: The Original Soundtrack from the Motion Picture',1978,14.4, 'Soundtrack'),
       ('Led Zeppelin','Led Zeppelin IV',1971,29.0,'Hard rock, Heavy metal, Folk'),
       ('Michael Jackson','Bad',1987,21.1, 'Pop, Funk, Rock'),
       ('Alanis Morissette','Jagged Little Pill',1995,24.3, 'Alternative rock'),
       ('Celine Dion','Falling into You',1996,21.1, 'Pop, Soft rock'),
       ('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band',1967,18.2, 'Rock'),
       ('Various Artists', 'Dirty Dancing', 1987, 17.9, 'Pop, rock, R&B'),
       ('Adele', '21', 1987, 26.4, 'Pop, soul'),
       ('Celine Dion', 'Let''s About Love', 1997, 19.3, 'Pop, soul'),
       ('Metallica', 'Metallica', 1991, 25.2, 'Heavy metal'),
       ('The Beatles', '1', 2000, 23.5, 'Rock'),
       ('The Beatles', 'Abbey Road', 1969, 14.4, 'Rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 23.0, 'Pop, disco'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 19.6, 'Heartland rock'),
       ('Madonna', 'The Immaculate Collection', 1990, 19.5, 'Pop, Dance'),
       ('Pink Floyd', 'The Wall', 1979, 18.7, 'Progressive Rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'Film score'),
       ('Dire Straits', 'Brother in Arms', 1985, 18.1, 'Roots rock, blues rock, soft rock'),
       ('Nirvana', 'Nevermind', 1991, 16.7, 'Grunge, alternative rock'),
       ('Santana', 'Supernatural', 1999, 20.5, 'Latin rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 21.9, 'Hard rock'),
       ('Elton John ', 'Goodbye Yellow Brink Road', 1973, 8.5, 'Rock, pop rock, glam rock');